### ISSUE TITLE
Error on setup: typo

### ISSUE THREAD

**Issue by MatElGran** [miguelfiguera/ror-book#3]
I was not able to load the schema locally because of the following error:

```shell
❯ bin/rails db:setup
rails aborted!
NoMethodError: undefined method `host' for #<Rails::Application::Configuration:0x0000000113a42928 @root=#<Pathname:/Users/mat/Code/ror-book>, @generators=#<Rails::Configuration::Generators:0x0000000112a381e0 @aliases={}, @options={:rails=>{:orm=>:active_record, :test_framework=>:test_unit, :integration_tool=>:test_unit, :system_tests=>:test_unit}, :active_record=>{:migration=>true, :timestamps=>true}, :test_unit=>{:fixture=>true, :fixture_replacement=>nil}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<Rails::Configuration::MiddlewareStackProxy:0x0000000113a42518 @operations=[], @delete_operations=[]>, @javascript_path="javascript", @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_parameters=[], @filter_redirect=[], @helpers_paths=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={:hsts=>{:subdomains=>true}}, @session_store=nil, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @railties_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000113a4ae98 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Rails::Application::Configuration::Custom:0x0000000113a4adf8 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=7.0, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/mat/Code/ror-book/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/mat/Code/ror-book/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Rails::Paths::Root:0x0000000113ccd1c0 @path=#<Pathname:/Users/mat/Code/ror-book>, @root={"app"=>#<Rails::Paths::Path:0x0000000113ccd008 @paths=["app"], @current="app", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Rails::Paths::Path:0x0000000113cccea0 @paths=["app/assets"], @current="app/assets", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Rails::Paths::Path:0x0000000113cccdd8 @paths=["app/controllers"], @current="app/controllers", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Rails::Paths::Path:0x0000000113cccd38 @paths=["app/channels"], @current="app/channels", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Rails::Paths::Path:0x0000000113cccc98 @paths=["app/helpers"], @current="app/helpers", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Rails::Paths::Path:0x0000000113cccbf8 @paths=["app/models"], @current="app/models", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Rails::Paths::Path:0x0000000113cccb58 @paths=["app/mailers"], @current="app/mailers", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Rails::Paths::Path:0x0000000113cccab8 @paths=["app/views"], @current="app/views", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Rails::Paths::Path:0x0000000113ccca18 @paths=["lib"], @current="lib", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Rails::Paths::Path:0x0000000113ccc950 @paths=["lib/assets"], @current="lib/assets", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Rails::Paths::Path:0x0000000113ccc8b0 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Rails::Paths::Path:0x0000000113ccc838 @paths=["config"], @current="config", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Rails::Paths::Path:0x0000000113ccc720 @paths=["config/environments"], @current="config/environments", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Rails::Paths::Path:0x0000000113ccc680 @paths=["config/initializers"], @current="config/initializers", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Rails::Paths::Path:0x0000000113ccc5e0 @paths=["config/locales"], @current="config/locales", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Rails::Paths::Path:0x0000000113ccc568 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Rails::Paths::Path:0x0000000113ccc4c8 @paths=["config/routes"], @current="config/routes", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Rails::Paths::Path:0x0000000113ccc450 @paths=["db"], @current="db", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Rails::Paths::Path:0x0000000113ccc3d8 @paths=["db/migrate"], @current="db/migrate", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Rails::Paths::Path:0x0000000113ccc360 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Rails::Paths::Path:0x0000000113ccc2c0 @paths=["vendor"], @current="vendor", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Rails::Paths::Path:0x0000000113ccc220 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Rails::Paths::Path:0x0000000113ccc180 @paths=["config/database.yml"], @current="config/database", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Rails::Paths::Path:0x0000000113ccc0e0 @paths=["config"], @current="config/secrets", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Rails::Paths::Path:0x0000000113ccc040 @paths=["config/environment.rb"], @current="config/environment", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Rails::Paths::Path:0x0000000113cd7fa8 @paths=["lib/templates"], @current="lib/templates", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Rails::Paths::Path:0x0000000113cd7eb8 @paths=["log/development.log"], @current="log", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Rails::Paths::Path:0x0000000113cd7e40 @paths=["public"], @current="public", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Rails::Paths::Path:0x0000000113cd7dc8 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Rails::Paths::Path:0x0000000113cd7d50 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Rails::Paths::Path:0x0000000113cd7cd8 @paths=["tmp"], @current="tmp", @root=#<Rails::Paths::Root:0x0000000113ccd1c0 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @cache_classes=false>
Did you mean?  hosts
/Users/mat/Code/ror-book/config/environments/development.rb:71:in `block in <main>'
/Users/mat/Code/ror-book/config/environments/development.rb:3:in `<main>'
/Users/mat/Code/ror-book/config/environment.rb:5:in `<main>'
Tasks: TOP => db:setup => db:create => db:load_config => environment
(See full trace by running task with --trace)
```

Since learning how to read stacktraces is an important part of the job, I'll let you figure out this one

**Comment by miguelfiguera** [comment]
Typo corrected.
